name: CI using Shared Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-shared-workflows:
    uses: parwaizmohammed/workflows/.github/workflows/reusable.yml@main
