name: expression and context workflow
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest

    env:
      MY_ENV_VAR: Hello,World!

    steps:
      - name: Set the value of MY_ENV_VAR
        run: echo "My_ENV_VAR=Hello, World!" >> $GITHUB_ENV

      - name: Print the environment variable
        run: echo ${{env.My_ENV_VAR}}
