name: First Workflow
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: one more string
        run: echo 'One more message'
      - name: Multiline Command
        run: |
          node -v
          npm -v
