name: First Workflow
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: one more string
        run: echo 'One more message'
      - name: Multiline Command
        run: |
          node -v
          npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_Vers
  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: run-shell-commands
        run: Write-Output "Window String"
      - name: Error Step
        run: doesnotexitssss
